version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: agentai-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped

  agentai:
    build: .
    container_name: agentai-app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
      - WORKERS=4
    volumes:
      - ./generated_projects:/app/generated_projects
      - ./web/data:/app/web/data
    restart: unless-stopped

volumes:
  redis_data: