# Application Settings

app:
  name: "coding-crew"
  version: "0.1.0"
  debug: true
  host: "0.0.0.0"
  port: 8000

# Database Configuration
database:
  url: "sqlite:///./coding_crew.db"
  echo: false

# Ollama Configuration
ollama:
  host: "localhost"
  port: 11434
  base_url: "http://localhost:11434"
  models:
    analysis: "ollama/llama3.1:8b"
    coding: "ollama/qwen2.5-coder:1.5b-base"
    review: "ollama/llama3.1:8b"
    testing: "ollama/qwen2.5-coder:1.5b-base"
    documentation: "ollama/llama3.2:latest"
    embedding: "ollama/nomic-embed-text:latest"

# Workflow Configuration
workflow:
  max_iterations:
    analysis: 5
    development: 5
    testing: 5
  timeout_seconds: 300

# Logging Configuration
logging:
  level: "INFO"
  format: "structured"
  file_rotation: "10 MB"
  retention_days: 7

# Cache Configuration
cache:
  type: "disk"  # disk, memory
  directory: "./cache"
  ttl_seconds: 3600

# Security Configuration
security:
  secret_key: "your-secret-key-here"
  algorithm: "HS256"
  access_token_expire_minutes: 30

# Feature Flags
features:
  enable_metrics: true
  enable_health_checks: true
  enable_diagram_generation: true
  enable_human_approval: true